---
- name: lib_openshift ensure python-ruamel-yaml package is on target
  package:
    name: python-ruamel-yaml
    state: present
  when:
    - ansible_distribution != "CentOS"

- name: required packages
  package: name={{ item }} state=installed
  with_items:
    - epel-release
    - python-pip
  when:
    - ansible_distribution == "CentOS"

- name: lib_openshift ensure ruamel.yaml package is on target with pip
  pip:
    name: ruamel.yaml
  when:
    - ansible_distribution == "CentOS"


